/**
 * Role catalogue. Permissions are declarative strings consumed by the
 * `authorize()` middleware, so access rules live in one place.
 */

const ROLES = [
  {
    code: 'command_center',
    label: 'Command Center',
    description: 'Monitors hospital state, runs surge simulation and requests resource optimisation.',
    permissions: [
      'dashboard:read',
      'queue:read',
      'beds:read',
      'doctors:read',
      'nurses:read',
      'equipment:read',
      'emergency-resources:read',
      'ot:read',
      'alerts:read',
      'alerts:write',
      'patients:read',
      'patients:write',
      'beds:write',
      'simulation:run',
      'optimization:request',
      'allocations:confirm',
      'allocations:reject',
      'approvals:decide',
      'notifications:read',
      'allocations:read',
    ],
  },
  {
    code: 'doctor',
    label: 'Doctor',
    description: 'Attends assigned patients, emergency cases, theatre list and own duty.',
    permissions: [
      'dashboard:read:own',
      'patients:read:own',
      'emergency:read:own',
      'ot:read:own',
      'beds:read',
      'icu:read',
      'duty:read:own',
      'tasks:write:own',
      'patients:confirm-requirement',
      'notifications:read:own',
      'alerts:read',
    ],
  },
  {
    code: 'nurse',
    label: 'Nurse',
    description: 'Attends assigned patients, ward beds, monitoring tasks and own duty.',
    permissions: [
      'dashboard:read:own',
      'patients:read:own',
      'emergency:read:own',
      'beds:read',
      'icu:read',
      'duty:read:own',
      'tasks:write:own',
      'notifications:read:own',
      'alerts:read',
    ],
  },
  {
    code: 'resource_coordinator',
    label: 'Resource Coordinator',
    description: 'Reviews recommendations, allocates beds/staff/equipment and approves requests.',
    permissions: [
      'dashboard:read',
      'allocations:read',
      'allocations:propose',
      'allocations:confirm',
      'allocations:reject',
      'approvals:read',
      'approvals:decide',
      'conflicts:read',
      'recommendations:review',
      'beds:write',
      'doctors:write',
      'nurses:write',
      'equipment:write',
      'ot:write',
      'queue:read',
      'patients:read',
      'alerts:read',
      'alerts:write',
      'notifications:read',
      'optimization:read',
    ],
  },
];

module.exports = { ROLES };
