/**
 * Clinical duty tasks — the clinical dashboard's own workload list.
 * Only doctors and nurses ever see these (role-scoped endpoint).
 */

const TASKS = [
  {
    reference: 'TSK-01',
    title: 'Review step-down candidates — ICU bays 02–07',
    detail: 'Six patients require a step-down review before the evening round; two are ventilator dependent.',
    category: 'Review',
    priority: 'High',
    dueTime: '11:00 AM',
    department: 'ICU',
    assignedDoctorId: 'DOC-1042',
    assignedNurseId: null,
  },
  {
    reference: 'TSK-02',
    title: 'Confirm ICU transfer checklist — IP-2214',
    detail: 'Transfer checklist must be confirmed before the step-down is recorded.',
    category: 'Transfer',
    priority: 'High',
    dueTime: '11:30 AM',
    department: 'ICU',
    assignedDoctorId: 'DOC-1161',
    assignedNurseId: null,
  },
  {
    reference: 'TSK-03',
    title: 'Assess new emergency admission — pending triage',
    detail: 'A patient in the emergency queue is awaiting clinical assessment before a resource requirement can be recorded.',
    category: 'Assessment',
    priority: 'Critical',
    dueTime: 'Immediate',
    department: 'Emergency',
    assignedDoctorId: 'DOC-1051',
    assignedNurseId: null,
  },
  {
    reference: 'TSK-04',
    title: 'Record resource requirement — P025 multi-resource case',
    detail: 'ICU bed, emergency theatre, ventilator and surgical support required simultaneously. Confirm the requirement so coordination can plan.',
    category: 'Coordination',
    priority: 'Critical',
    dueTime: 'Immediate',
    department: 'Emergency',
    assignedDoctorId: 'DOC-1083',
    assignedNurseId: null,
  },
  {
    reference: 'TSK-05',
    title: 'Post-operative review — IP-2205',
    detail: 'Analgesia and mobilisation review after laparotomy. Dressing check due.',
    category: 'Review',
    priority: 'Medium',
    dueTime: '12:15 PM',
    department: 'Intensive Care',
    assignedDoctorId: 'DOC-1081',
    assignedNurseId: null,
  },
  {
    reference: 'TSK-06',
    title: 'Confirm ICU transfer checklist — IP-2214 (nursing)',
    detail: 'Transfer checklist and monitoring requirements must be confirmed before step-down.',
    category: 'Transfer',
    priority: 'High',
    dueTime: '11:45 AM',
    department: 'ICU',
    assignedDoctorId: null,
    assignedNurseId: 'NUR-201',
  },
  {
    reference: 'TSK-07',
    title: 'Hourly observation charting — ICU bays 02–06',
    detail: 'Five patients require hourly observations; two are on ventilation support.',
    category: 'Monitoring',
    priority: 'High',
    dueTime: 'Hourly',
    department: 'ICU',
    assignedDoctorId: null,
    assignedNurseId: 'NUR-201',
  },
  {
    reference: 'TSK-08',
    title: 'Medication round — ICU-02 to ICU-10',
    detail: 'Scheduled medication round including inotrope and insulin infusions.',
    category: 'Medication',
    priority: 'Medium',
    dueTime: '12:30 PM',
    department: 'ICU',
    assignedDoctorId: null,
    assignedNurseId: 'NUR-201',
  },
  {
    reference: 'TSK-09',
    title: 'Prepare a monitored bay for incoming admission',
    detail: 'Emergency intake: prepare the bay with oxygen, monitor and resuscitation trolley.',
    category: 'Emergency preparedness',
    priority: 'Critical',
    dueTime: 'Immediate',
    department: 'Emergency',
    assignedDoctorId: null,
    assignedNurseId: 'NUR-301',
  },
  {
    reference: 'TSK-10',
    title: 'Ventilator circuit check — ICU-01 to ICU-08',
    detail: 'Circuit integrity and humidifier checks for ventilated patients.',
    category: 'Monitoring',
    priority: 'High',
    dueTime: '01:00 PM',
    department: 'ICU',
    assignedDoctorId: null,
    assignedNurseId: 'NUR-202',
  },
  {
    reference: 'TSK-11',
    title: 'Confirm OT equipment readiness — OT-02',
    detail: 'Anaesthesia workstation, C-arm and diathermy readiness for the 11:30 AM list.',
    category: 'Theatre',
    priority: 'Medium',
    dueTime: '11:15 AM',
    department: 'OT Complex',
    assignedDoctorId: null,
    assignedNurseId: 'NUR-503',
  },
  {
    reference: 'TSK-12',
    title: 'Ward bed preparation — General Ward (4 beds)',
    detail: 'Prepare four general beds for the emergency queue admissions pending allocation.',
    category: 'Preparedness',
    priority: 'Medium',
    dueTime: '12:00 PM',
    department: 'General Ward',
    assignedDoctorId: null,
    assignedNurseId: 'NUR-405',
  },
];

module.exports = { TASKS };
